language: node_js
node_js:
  - 8
before_script:
  - echo 'start'
script:
  - npm run build
after_success:
  - echo 'done'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: U9BhEcu5MEvvzspGigTp
  on:
    branch: master